version: '4.40.0'

services:
  main-app:
    build:
      context: ./main-app
      dockerfile: main-app/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db-postgres
      - db-redis
    environment:
      - 'SPRING_R2DBC_URL=r2dbc:postgresql://db:5432/postgres'
      - 'SPRING_R2DBC_USERNAME=compose-postgres'
      - 'SPRING_R2DBC_PASSWORD=compose-postgres'

  payment-app:
    build:
      context: ./payment-app
      dockerfile: payment-app/Dockerfile
    ports:
      - "8081:8081"

  db-postgres:
    image: 'postgres:17'
    restart: always
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres

  db-redis:
    image: 'redis:7.4.2-bookworm'