version: '4.40.0'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - 'SPRING_R2DBC_URL=r2dbc:postgresql://db:5432/postgres'
      - 'SPRING_R2DBC_USERNAME=compose-postgres'
      - 'SPRING_R2DBC_PASSWORD=compose-postgres'
  db:
    image: 'postgres:17'
    restart: always
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres