services:
  main-app:
    build:
      context: ./main-app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db-postgres
      - payment-app
      - cache-redis
    environment:
      - 'SPRING_R2DBC_URL=r2dbc:postgresql://db-postgres:5432/postgres'
      - 'SPRING_R2DBC_USERNAME=compose-postgres'
      - 'SPRING_R2DBC_PASSWORD=compose-postgres'
      - 'SPRING_DATA_REDIS_HOST=cache-redis'
      - 'PAYMENT_SERVICE=http://payment-app:8081'

  payment-app:
    build:
      context: ./payment-app
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

  db-postgres:
    image: 'postgres:17'
    restart: always
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres

  cache-redis:
    image: 'redis:7.4.2-bookworm'
    restart: always