CREATE TABLE IF NOT EXISTS users
(
    username character varying(255),
    password character varying(255),
    balance double precision DEFAULT 100000.00,
    CONSTRAINT users_pkey PRIMARY KEY (username)
);

insert into users(username, password) values ('default', '$2a$12$rfG90Tzo1Aw8lJjWNSZtE.eAkESMBjtiOJb0OYjUeAqqEuwTwKX9.');
insert into users(username, password) values ('admin', '$2a$12$VpSv2dSt29.WFb3ey4oyJOnwDgC8AINe6fC88ScbX1zoPNdy/VYjS');


CREATE TABLE IF NOT EXISTS items
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    description character varying(255),
    image bytea,
    item_name character varying(255),
    price double precision,
    CONSTRAINT items_pkey PRIMARY KEY (id)
);


insert into items(item_name, description, price) values ('Item 1', 'Proin a orci et ipsum accumsan porttitor ac non est.', 12);
insert into items(item_name, description, price) values ('Item 2', 'Description', 234234.7);
insert into items(item_name, description, price) values ('Item 3', 'Test', 1200);


CREATE TABLE IF NOT EXISTS orders
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    username character varying(255) NOT NULL,
    CONSTRAINT orders_pkey PRIMARY KEY (id),
    CONSTRAINT orders_user_fk FOREIGN KEY (username)
        REFERENCES users (username) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS orders_items
(
    count integer DEFAULT 1,
    item_id bigint NOT NULL,
    order_id bigint NOT NULL,
    CONSTRAINT orders_items_pkey PRIMARY KEY (item_id, order_id),
    CONSTRAINT orders_items_item_fk FOREIGN KEY (item_id)
        REFERENCES items (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT orders_items_order_fk FOREIGN KEY (order_id)
        REFERENCES orders (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);