CREATE TABLE IF NOT EXISTS items
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    description character varying(255),
    image bytea,
    item_name character varying(255),
    price double precision,
    CONSTRAINT items_pkey PRIMARY KEY (id)
);


insert into items(item_name, description, price) values ('Item 1', 'Proin a orci et ipsum accumsan porttitor ac non est.', 12);
insert into items(item_name, description, price) values ('Item 2', 'Description', 234234.7);
insert into items(item_name, description, price) values ('Item 3', 'Test', 1200);


CREATE TABLE IF NOT EXISTS orders
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT orders_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS orders_items
(
    count integer DEFAULT 1,
    item_id bigint NOT NULL,
    order_id bigint NOT NULL,
    CONSTRAINT orders_items_pkey PRIMARY KEY (item_id, order_id),
    CONSTRAINT orders_items_item_fk FOREIGN KEY (item_id)
        REFERENCES items (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT orders_items_order_fk FOREIGN KEY (order_id)
        REFERENCES orders (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);